import { mdxComponents as baseMdxComponents } from "../ui/mdx";
import { defaultLayouts } from "./layouts/defaultLayouts";
import type {
  ResolvedSlideTheme,
  SlideThemeDefinition,
  ThemeMDXComponents,
} from "./types";

// @ts-expect-error -- virtual module generated by slidev-react:themes Vite plugin
import activeTheme from "virtual:slidev-react/active-theme";

const defaultTheme: SlideThemeDefinition = {
  id: "default",
  label: "Default",
  colorScheme: "light",
  rootAttributes: {
    "data-slide-theme": "default",
  },
};

export function resolveSlideTheme(): ResolvedSlideTheme {
  const definition: SlideThemeDefinition = activeTheme ?? defaultTheme;

  return {
    definition,
    rootAttributes: definition.rootAttributes ?? {
      "data-slide-theme": definition.id,
    },
    rootClassName: definition.rootClassName,
    provider: definition.provider,
    layouts: {
      ...defaultLayouts,
      ...definition.layouts,
    },
    mdxComponents: {
      ...baseMdxComponents,
      ...definition.mdxComponents,
    },
  };
}
