import { mdxComponents as baseMdxComponents } from "../ui/mdx";
import kamiTheme from "./builtin/kami";
import { defaultLayouts } from "./layouts/defaultLayouts";
import type { ResolvedSlideTheme, SlideThemeDefinition } from "./types";

// @ts-expect-error -- virtual module generated by slidev-react:themes Vite plugin
import activeTheme from "virtual:slidev-react/active-theme";

/**
 * Kami is the design language, so a deck that names no theme still renders as Kami
 * rather than falling back to a bare token set with no layouts or components.
 */
const fallbackTheme: SlideThemeDefinition = kamiTheme;

export function resolveSlideTheme(): ResolvedSlideTheme {
  const definition: SlideThemeDefinition = activeTheme ?? fallbackTheme;

  return {
    definition,
    tokens: definition.tokens,
    rootAttributes: definition.rootAttributes ?? {
      "data-slide-theme": definition.id,
    },
    rootClassName: definition.rootClassName,
    provider: definition.provider,
    layouts: {
      ...defaultLayouts,
      ...definition.layouts,
    },
    mdxComponents: {
      ...baseMdxComponents,
      ...definition.mdxComponents,
    },
  };
}
