import type { SlideAddonDefinition } from "../../types";
import { EditorialCover } from "./EditorialCover";
import { EditorialDivider } from "./EditorialDivider";
import { EditorialSlide } from "./EditorialSlide";
import {
  EdEyebrow,
  EdTitle,
  EdH2,
  EdLede,
  EdCard,
  EdCallout,
  EdInsight,
  EdVsRow,
  EdVsCol,
  EdVsSep,
  EdVsList,
  EdVsItem,
  EdWin,
  EdScoreboard,
  EdScorePanel,
  EdNumList,
  EdNumItem,
  EdStatement,
  EdBarRow,
  EdTreeBand,
  EdSwatch,
  EdTreeLayer,
  EdTreeNode,
  EdCode,
  EdKw,
  EdGrid,
  EdTable,
  EdThead,
  EdTh,
  EdTd,
  EdStatus,
  EdSectionTitle,
  EdCheckItem,
  EdTaskItem,
  EdSubHeading,
  EdScore,
  EdDisclaimer,
  EdProjectTag,
  EdBrandCard,
  EdCoverTitle,
  EdMark,
  EdLink,
  EdSummaryCard,
  EdBrandLabel,
  EdBarLabel,
  EdImage,
} from "./EditorialComponents";

export const addon: SlideAddonDefinition = {
  id: "editorial",
  label: "Editorial",
  experimental: true,
  mdxComponents: {
    EditorialCover,
    EditorialDivider,
    EditorialSlide,
    EdEyebrow,
    EdTitle,
    EdH2,
    EdLede,
    EdCard,
    EdCallout,
    EdInsight,
    EdVsRow,
    EdVsCol,
    EdVsSep,
    EdVsList,
    EdVsItem,
    EdWin,
    EdScoreboard,
    EdScorePanel,
    EdNumList,
    EdNumItem,
    EdStatement,
    EdBarRow,
    EdTreeBand,
    EdSwatch,
    EdTreeLayer,
    EdTreeNode,
    EdCode,
    EdKw,
    EdGrid,
    EdTable,
    EdThead,
    EdTh,
    EdTd,
    EdStatus,
    EdSectionTitle,
    EdCheckItem,
    EdTaskItem,
    EdSubHeading,
    EdScore,
    EdDisclaimer,
    EdProjectTag,
    EdBrandCard,
    EdCoverTitle,
    EdMark,
    EdLink,
    EdSummaryCard,
    EdBrandLabel,
    EdBarLabel,
    EdImage,
  },
};
